[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "cd inacap_reporta && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd inacap_reporta && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd inacap_reporta && gunicorn inacap_reporta.wsgi --log-file -"

[deploy]
releaseCommand = "cd inacap_reporta && python manage.py migrate --noinput && python manage.py create_superuser_if_not_exists"



